# Generated by Django 5.2 on 2025-04-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeproposal',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидает'), ('accepted', 'Принята'), ('rejected', 'Отклонена')], default='waiting', max_length=20, verbose_name='Статус'),
        ),
    ]
